import fs from 'node:fs'
import assert from 'node:assert/strict'

const source = fs.readFileSync(new URL('../plugin.js', import.meta.url), 'utf8')
const version = fs.readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim()

assert.match(source, /const ID = 'hermes-mender'/)
assert.ok(source.includes("const VERSION = '" + version + "'"))

assert.match(source, /host\.request\('plugins\.manage'/)
assert.match(source, /action: 'install'/)
assert.match(source, /ref: sha/)
assert.match(source, /force: false/)
assert.doesNotMatch(source, /force:\s*true/)
assert.match(source, /action: 'toggle'/)
assert.match(source, /action: 'update'/)
assert.match(source, /consent_required/)
assert.doesNotMatch(source, /accept_capabilities\s*:\s*true/)
assert.match(source, /installDesktopPlugin/)
assert.match(source, /probePluginRepo/)
assert.match(source, /discoverDesktopOnlyUpdateItems/)
assert.match(source, /applyDesktopOnlyUpdateItem/)
assert.doesNotMatch(source, /updateDesktopOnlyPackages/)
assert.doesNotMatch(source, /legacyUpdateAllPluginsMutating/)
assert.match(source, /watchDirectory/)

assert.match(source, /respectUninstallIntent/)
assert.match(source, /repair\.respectUninstallIntent/)
assert.match(source, /repair\.autoEnableAgents/)
assert.match(source, /Respect uninstall actions/)
assert.match(source, /Auto-enable repaired Agent halves/)
assert.match(source, /Automatic repair/)
assert.match(source, /repair\.scheduleMode/)
assert.match(source, /repair\.intervalSeconds/)
assert.match(source, /AUTO_REPAIR_FALLBACK_MS/)
assert.match(source, /maxHeight: '560px'/)
assert.match(source, /maxHeight: '240px'/)
assert.match(source, /Update all/)
assert.match(source, /Check updates/)
assert.match(source, /Review updates/)
assert.match(source, /Automatic update checks/)
assert.match(source, /updates\.checkMode/)
assert.match(source, /updates\.intervalSeconds/)
assert.match(source, /MENDER_REPOSITORY/)
assert.match(source, /discoverMenderSelfUpdate/)
assert.match(source, /updatePlanState/)
assert.match(source, /dedupeUpdateItems/)
assert.match(source, /async function updateAllPlugins\(\) \{\s*await openUpdateReviewForAll\(\)\s*\}/)
assert.match(source, /openUpdateReviewForPlugin\(item\.catalog\)/)
assert.match(source, /Nothing is installed until you confirm here/)
assert.match(source, /applyConfirmedUpdates/)
assert.match(source, /isHermesScannerBlockedResult/)
assert.match(source, /Repair now/)
assert.match(source, /children: item\.agentStatus === 'enabled' \? 'Disable' : 'Enable'/)
assert.match(source, /uninstallConfirmItem/)
assert.match(source, /DialogContent/)
assert.match(source, /DialogTitle/)
assert.match(source, /variant: 'destructive'/)
assert.doesNotMatch(source, /window\.confirm/)
assert.match(source, /children: 'Uninstall'/)

assert.match(source, /SECURITY_MODES/)
assert.match(source, /CORE_PROTECTION_MODES/)
assert.match(source, /coreProtection\.mode/)
assert.match(source, /coreProtection\.approvals/)
assert.match(source, /Smart: detected Core tampering pauses and asks/)
assert.match(source, /Strict: detected Core tampering is blocked/)
assert.match(source, /Off: Mender allows Core tampering/)
assert.match(source, /Strict has no per-version bypass/)
assert.match(source, /Allow this exact version/)
assert.match(source, /Compatibility ·/)
assert.match(source, /checkCompatibility/)
assert.match(source, /evaluateCompatibilityChecks/)
assert.match(source, /Required Hermes APIs are missing/)
assert.match(source, /Automatic Mender mutations are paused/)
assert.match(source, /does not carry to updates/)
assert.match(source, /coreApprovalKey/)
assert.match(source, /preflightDecision/)

assert.match(source, /Install from GitHub/)
assert.match(source, /gridTemplateColumns: 'minmax\(0, 3fr\) minmax\(360px, 2fr\)'/)
assert.match(source, /Install & enable/)
assert.match(source, /Enable after install/)
assert.match(source, /install\.enableAfterDefault/)
assert.match(source, /installFromInput\(false\)/)
assert.match(source, /installFromInput\(true\)/)
assert.match(source, /result\?\.plugin_name/)
assert.match(source, /action: 'toggle'/)
assert.match(source, /enable: false/)
assert.match(source, /installIdentifier/)
assert.match(source, /installEnableAfterDefault/)
assert.match(source, /host\.notify\?\.\(\{ kind: 'success'/)
assert.match(source, /desktopSatisfiedFromAgentPackage/)
assert.match(source, /reconcileDesktopPlugins\(\)/)
assert.match(source, /parseGitHubInstallIdentifier/)
assert.match(source, /resolveGitHubInstallSha/)
assert.match(source, /Public GitHub repositories only/)
assert.match(source, /Repository changed while being checked/)
assert.match(source, /if \(!target\.ref\)/)
assert.match(source, /exact-SHA tree Mender already fetched is the shape authority/)
assert.match(source, /requested GitHub ref does not contain a supported Hermes plugin package/)
assert.match(source, /reviewFindings/)
assert.match(source, /capabilityChanges/)
assert.match(source, /Check compatibility/)
assert.match(source, /Compatible/)
assert.match(source, /Degraded/)
assert.match(source, /Unsupported/)

assert.match(source, /ROUTES_AREA/)
assert.match(source, /STATUSBAR_AREAS\.right/)
assert.match(source, /path: '\/mender'/)
assert.match(source, /MenderPage/)
assert.match(source, /MenderStatus/)
assert.match(source, /mender-state\.json/)
assert.match(source, /by @milanworks/)
assert.match(source, /gridTemplateColumns: 'minmax\(0, 3fr\) minmax\(360px, 2fr\)'/)

console.log('mender-contract: ok (' + version + ')')
