import fs from 'node:fs'
import assert from 'node:assert/strict'

const source = fs.readFileSync(new URL('../plugin.js', import.meta.url), 'utf8')
const version = fs.readFileSync(new URL('../VERSION', import.meta.url), 'utf8').trim()

assert.match(source, /const ID = 'hermes-mender'/)
assert.ok(source.includes("const VERSION = '" + version + "'"))

assert.match(source, /host\.request\('plugins\.manage'/)
assert.match(source, /action: 'install'/)
assert.match(source, /catalog_name: entry\.name/)
assert.match(source, /autoEnableRepairedAgents\.get\(\)/)
assert.match(source, /action: 'toggle'/)
assert.match(source, /key: item\.agentKey/)
assert.match(source, /action: 'update'/)
assert.match(source, /consent_required/)
assert.doesNotMatch(source, /accept_capabilities\s*:\s*true/)

assert.match(source, /installDesktopPlugin/)
assert.match(source, /force: false/)
assert.doesNotMatch(source, /force:\s*true/)
assert.match(source, /updateDesktopOnlyPackages/)
assert.match(source, /desktopUpdateTextFile/)
assert.match(source, /watchDirectory/)

assert.match(source, /respectUninstallIntent/)
assert.match(source, /repair\.respectUninstallIntent/)
assert.match(source, /repair\.autoEnableAgents/)
assert.match(source, /Respect uninstall actions/)
assert.match(source, /Auto-enable repaired Agent halves/)
assert.match(source, /Update all/)
assert.match(source, /Repair now/)
assert.match(source, /children: 'Enable'/)

assert.match(source, /hasBlockingFinding/)
assert.match(source, /SECURITY_MODES/)
assert.match(source, /security\.mode/)
assert.match(source, /Smart:/)
assert.match(source, /Strict:/)
assert.match(source, /Off:/)
assert.match(source, /scanSource/)
assert.match(source, /MND001/)
assert.match(source, /MND003/)
assert.match(source, /hermes-core-update-blocked/)
assert.match(source, /update-review-required/)

assert.match(source, /ROUTES_AREA/)
assert.match(source, /STATUSBAR_AREAS\.right/)
assert.match(source, /path: '\/mender'/)
assert.match(source, /MenderPage/)
assert.match(source, /MenderStatus/)
assert.match(source, /mender-state\.json/)
assert.match(source, /by @milanworks/)

console.log('mender-contract: ok (' + version + ')')